# This file was generated by GoReleaser. DO NOT EDIT.
cask "kvd" do
  name "kvd"
  desc "A dumb Redis-compatible key-value database using Docker as storage"
  homepage "https://github.com/YungBricoCoop/kvd"
  version "0.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kvd"

  on_macos do
    on_intel do
      url "https://github.com/YungBricoCoop/kvd/releases/download/v#{version}/kvd_Darwin_x86_64.tar.gz"
      sha256 "38a5078445e1d553754d718316e0df23be312b063f7dba7e4a72355ebf812a57"
    end
    on_arm do
      url "https://github.com/YungBricoCoop/kvd/releases/download/v#{version}/kvd_Darwin_arm64.tar.gz"
      sha256 "b842ca18bec538e4af8ace6e003cd8809a2e7a393b6c0ced2feef2c915ae8b74"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/YungBricoCoop/kvd/releases/download/v#{version}/kvd_Linux_x86_64.tar.gz"
      sha256 "305c6807e28df733c1e3bbcc4c9bdd17a388a551902e18a124ac84a20a0b935c"
    end
    on_arm do
      url "https://github.com/YungBricoCoop/kvd/releases/download/v#{version}/kvd_Linux_arm64.tar.gz"
      sha256 "c8a5876be522387418b356ff3a455b0d6106579784bcf190ce11a232eddcadb7"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kvd"]
    end
  end

  # No zap stanza required
end
